name: hello_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.0.2
  provider: ^2.0.0+1

  cupertino_icons: ^0.1.2
  flare_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/star.png
    - assets/nature/